version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - first:/var/www/first
      - second:/var/www/second
  first:
    build:
      context: first-app
      dockerfile: Dockerfile
    volumes:
      - first:/app/build
  second:
    build:
      context: first-app
      dockerfile: Dockerfile
    volumes:
      - second:/app/build
volumes:
  first:
  second: